# Intensity

In this notebook we conduct measurements with the photodiode and different constellations of the acousto-optic deflectors.

In [2]:
import os
import control
import numpy as np
import pandas as pd

from time import sleep
from matplotlib import pyplot as plt

os.makedirs('../dataset/intensity', exist_ok=True)

control.aom()
control.aod_h(frequency=100e6)
control.aod_v(frequency=100e6)

scope = control.MSOX6004A('172.22.22.30')
scope.holla()

'AGILENT TECHNOLOGIES,MSO-X 4054A,MY57310545,07.20.2017102615\n'

In [72]:
def data_to_hdf(filename, fieldname, data):
    df = pd.DataFrame({'time': data[0][1]['time'], **{f'voltage@{d[0]:.2f}': d[1]['voltage'] for d in data}})
    df.to_hdf(filename, fieldname, complevel=9)
    
    return df

In [74]:
data = []

for A in np.arange(0.2, 1.02, .02):
    control.aod_h(frequency=[90e6, 110e6], duration=26.84e-3, amplitude=A*np.ones(1024), nodwells=[False, True])

    data.append((A, scope.capture()))

data_to_hdf('../dataset/intensity/unpaired.h5', 'horizontal_element_horizontal_socket', data).head(5)

,time,voltage@0.20,voltage@0.22,voltage@0.24,voltage@0.26,voltage@0.28,voltage@0.30,voltage@0.32,voltage@0.34,voltage@0.36,...,voltage@0.82,voltage@0.84,voltage@0.86,voltage@0.88,voltage@0.90,voltage@0.92,voltage@0.94,voltage@0.96,voltage@0.98,voltage@1.00
0,-0.000394,1.324326,1.530518,1.762485,2.020225,2.277966,2.587254,2.948091,3.334702,3.669765,...,5.370852,5.319304,5.241982,5.241982,5.164660,5.087338,5.010015,4.984241,4.958467,4.932693
1,-0.000393,1.324326,1.504744,1.788259,1.994451,2.303740,2.587254,2.948091,3.360476,3.695539,...,5.345078,5.293530,5.216208,5.190434,5.164660,5.087338,5.035789,5.035789,4.932693,4.932693
2,-0.000393,1.324326,1.530518,1.814033,2.045999,2.277966,2.638802,2.973865,3.386250,3.669765,...,5.345078,5.319304,5.241982,5.190434,5.138886,5.113112,5.035789,5.010015,5.010015,4.906919
3,-0.000392,1.298552,1.504744,1.736711,1.994451,2.329514,2.638802,2.948091,3.334702,3.643991,...,5.370852,5.319304,5.216208,5.241982,5.138886,5.113112,5.010015,5.010015,4.958467,4.932693
4,-0.000392,1.350100,1.504744,1.736711,2.020225,2.303740,2.613028,2.922317,3.334702,3.669765,...,5.370852,5.319304,5.216208,5.216208,5.164660,5.087338,5.035789,4.984241,4.984241,4.906919

In [81]:
data = []

for A in np.arange(0.2, 1.02, .02):
    control.aod_h(frequency=[90e6, 110e6], duration=26.84e-3, amplitude=A*np.ones(1024), nodwells=[False, True])

    data.append((A, scope.capture()))

data_to_hdf('../dataset/intensity/unpaired.h5', 'horizontal_element_vertical_socket', data).head(5)

,time,voltage@0.20,voltage@0.22,voltage@0.24,voltage@0.26,voltage@0.28,voltage@0.30,voltage@0.32,voltage@0.34,voltage@0.36,...,voltage@0.82,voltage@0.84,voltage@0.86,voltage@0.88,voltage@0.90,voltage@0.92,voltage@0.94,voltage@0.96,voltage@0.98,voltage@1.00
0,-0.000394,0.066046,0.084456,0.102866,0.102866,0.102866,0.102866,0.139686,0.139686,0.139686,...,0.434247,0.434247,0.434247,0.452657,0.452657,0.452657,0.489477,0.471067,0.452657,0.489477
1,-0.000393,0.084456,0.066046,0.102866,0.084456,0.139686,0.102866,0.139686,0.158096,0.139686,...,0.434247,0.397427,0.452657,0.434247,0.434247,0.452657,0.452657,0.471067,0.489477,0.471067
2,-0.000393,0.066046,0.084456,0.102866,0.084456,0.084456,0.121276,0.102866,0.121276,0.176506,...,0.434247,0.452657,0.434247,0.452657,0.471067,0.452657,0.452657,0.471067,0.471067,0.489477
3,-0.000392,0.066046,0.102866,0.066046,0.084456,0.066046,0.121276,0.121276,0.121276,0.158096,...,0.434247,0.452657,0.452657,0.434247,0.452657,0.471067,0.452657,0.471067,0.471067,0.489477
4,-0.000392,0.084456,0.066046,0.084456,0.102866,0.084456,0.139686,0.139686,0.139686,0.102866,...,0.434247,0.434247,0.452657,0.434247,0.434247,0.434247,0.434247,0.471067,0.471067,0.489477

In [89]:
data = []

for A in np.arange(0.2, 1.02, .02):
    control.aod_h(frequency=[90e6, 110e6], duration=26.84e-3, amplitude=A*np.ones(1024), nodwells=[False, True])

    data.append((A, scope.capture()))

data_to_hdf('../dataset/intensity/unpaired.h5', 'vertical_element_vertical_socket', data).head(5)

,time,voltage@0.20,voltage@0.22,voltage@0.24,voltage@0.26,voltage@0.28,voltage@0.30,voltage@0.32,voltage@0.34,voltage@0.36,...,voltage@0.82,voltage@0.84,voltage@0.86,voltage@0.88,voltage@0.90,voltage@0.92,voltage@0.94,voltage@0.96,voltage@0.98,voltage@1.00
0,-0.000394,0.093515,0.110251,0.110251,0.110251,0.110251,0.126987,0.143724,0.143724,0.143724,...,0.57887,0.562134,0.578870,0.595607,0.595607,0.595607,0.612343,0.629079,0.629079,0.629079
1,-0.000393,0.093515,0.093515,0.093515,0.110251,0.126987,0.126987,0.143724,0.126987,0.177197,...,0.57887,0.578870,0.562134,0.595607,0.612343,0.612343,0.629079,0.629079,0.612343,0.612343
2,-0.000393,0.076778,0.093515,0.093515,0.110251,0.110251,0.126987,0.160460,0.160460,0.160460,...,0.57887,0.578870,0.562134,0.595607,0.595607,0.612343,0.612343,0.612343,0.612343,0.629079
3,-0.000392,0.076778,0.093515,0.110251,0.126987,0.093515,0.126987,0.143724,0.143724,0.160460,...,0.57887,0.562134,0.578870,0.612343,0.612343,0.612343,0.629079,0.629079,0.612343,0.612343
4,-0.000392,0.076778,0.060042,0.093515,0.110251,0.110251,0.126987,0.143724,0.143724,0.177197,...,0.57887,0.562134,0.595607,0.595607,0.612343,0.612343,0.629079,0.629079,0.629079,0.645816

In [ ]:
data = []

for A in np.arange(0.2, 1.02, .02):
    control.aod_h(frequency=[90e6, 110e6], duration=26.84e-3, amplitude=A*np.ones(1024), nodwells=[False, True])

    data.append((A, scope.capture()))

data_to_hdf('../dataset/intensity/unpaired.h5', 'vertical_element_horizontal_socket', data).head(5)